language: c

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq asciidoc cppcheck libarchive-dev liblzma-dev xz-utils

script:
  - autoconf --version
  - ./autogen.sh
  - ./configure
  - make
  - make check
