sudo: false

language: c

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - asciidoc
      - libarchive-dev
      - liblzma-dev
      - xz-utils

script:
  - autoconf --version
  - ./autogen.sh
  - ./configure
  - make
  - make check
